# Generated by Django 2.0.7 on 2018-07-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0002_userdetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='isMarried',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
