# Generated by Django 2.0.7 on 2018-07-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0003_userdetails_ismarried'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='isMarried',
        ),
    ]
